name = "koperasi-warga-lima-sejahtera"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "koperasi_db"
database_id = "ISI_DATABASE_ID_D1_ANDA"
